### ISSUE TITLE
Использовать parent selector и вложенные media queries

### ISSUE THREAD

**Issue by isquariel** [KiraShubik/Pink#12]
Вместо того, чтобы писать так:
```less
.product__item {
    // Какой-то код
}

.product__item:last-child {
    border-bottom: solid  2px #e5e5e5;
}
.product__item_included_yes {
    background-image: url(../img/icon_yes.png);
}
.product__item_included_no {
    background-image: url(../img/icon_no.png);
}
```
Можно писать вот так:
```less
.product__item {
    // Какой-то код

    &:last-child {
        border-bottom: solid  2px #e5e5e5;
    }

    &_included_yes {
        background-image: url(../img/icon_yes.png);
    }

    &_included_no {
        background-image: url(../img/icon_no.png);
    }
}
```
Эта фича LESS называется [parent selector](http://lesscss.org/features/#parent-selectors-feature).

Ещё можно сложить media queries в переменные вот так:
```less
// В variables.less
@tablet: ~"only screen and (min-width: 700px)";
@desktop: ~"only screen and (min-width: 1200px)";

// В любом файле с media queries
@media @tablet {
    // Какие-то стили
}
```

И, наконец, можно media queries писать прямо внутри селектора:
```less
.product {
    margin: 0 0 30px;

    @media @tablet {
         margin-bottom: 110px;
    }

    @media @desktop {
        margin-bottom: 80px; // Это пример, а не реальные значения.
    }
}
```

Задача: привести все LESS-файлы к такому виду. Но не увлекайся с `&`. Рекомендую тебе использовать его только в модификаторах, псевдо-классах и псевдо-элементах, но не использовать в отношении блок-элемент. Вот так не делать:
```less
.product {
    // Какие-то стили

    &__item {
        // Какие-то стили
    }
}
```
Потому что `&` лучше (на мой субъективный взгляд) использовать для одного элемента в разных вариантах (с модификаторами, с last-child и пр., c hover), а не для вложенных элементов.
