### ISSUE TITLE
Привести в порядок картинки

### ISSUE THREAD

**Issue by isqua** [KiraShubik/Pink#14]
1) Назвать картинки в соответствии с элементом, для которого они нужны, все буквы в именах файлов должны быть строчными:
```css
.feature__image_type_mood {
    /* Сейчас название картинки не говорит о том, для какого блока она нужна.
       Оно сообщает только, что картинка про айфон. Если назвать её feature__image_type_mood,
       будет понятно, где она используется. */
    background-image: url(../img/Iphone_decstop_left.png);
}
```
2) Всё, что можно сделать векторным, следует сделать в SVG.
3) А растровые картинки подготовить для ретины и *правильно* прописать в стилях.
4) Неиспользуемые картинки удалить.
